config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  # rsvp
  get '/rsvp', to: 'rsvp#new', as: :rsvp_new
  post '/rsvp', to: 'rsvp#create', as: :rsvps
  get '/rsvp/list', to: 'rsvp#list', as: :rsvp_list

  # our story
  get '/our-story', to: 'static#our_story'

  # details
  get '/details', to: 'static#details'

  # registry
  get '/registry', to: 'static#registry'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  validates_presence_of :full_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new rsvp_create_params
    if @rsvp.save!
      render 'success'
    else
      render 'new'
    end
  end

  def list
    @rsvps = Rsvp.all
    render 'list'
  end

  private

  def rsvp_create_params
    params.require(:rsvp).permit(:full_name, :is_coming, :has_plus_one, :plus_one_full_name)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def our_story
  end

  def details
  end

  def registry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_string(css_map)
    css_map.find_all(&:last).map(&:first).join(" ")
  end

  def nav_classes_for(path)
    class_string("nav-link": true, "active": current_page?(path))
  end
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_nav.html.erb
<nav>
    <ul class="nav nav-pills justify-content-center">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: nav_classes_for(root_path) %>
        </li>
        <li class="nav-item">
            <%= link_to "RSVP", rsvp_new_path, class: nav_classes_for(rsvp_new_path)%>
        </li>
        <li class="nav-item">
            <%= link_to "Our Story", our_story_path, class: nav_classes_for(our_story_path) %>
        </li>
        <li class="nav-item">
            <%= link_to "Details", details_path, class: nav_classes_for(details_path) %>
        </li>
        <li class="nav-item">
            <%= link_to "Registry", registry_path, class: nav_classes_for(registry_path) %>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>FoleyWedding</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>

    <body>
        <%= render 'layouts/nav' %>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rsvp/list.html.erb
<h1>RSVPs</h1>
<div class="container">
    <div class=row>
        <div class="col-4">
            Full Name
        </div>
        <div class="col-2">
            Is Coming
        </div>
        <div class="col-2">
            Has Plus One
        </div>
        <div class="col-4">
            Plus One Full Name
        </div>
    </div>
    <% @rsvps.each do |rsvp| %>
        <div class="row">
            <div class="col-4">
                <%= rsvp.full_name %>
            </div>
            <div class="col-2">
                <%= rsvp.is_coming %>
            </div>
            <div class="col-2">
                <%= rsvp.has_plus_one %>
            </div>
            <div class="col-4">
                <%= rsvp.plus_one_full_name %>
            </div>
        </div>
    <% end %>
</div>

app/views/rsvp/new.html.erb
<section class="container">
    <h1>RSVP</h1>
    <%= form_for @rsvp do |f| %>
        <div class="form-group row">
            <%= f.label :full_name, class: 'col-2 col-sm-4 col-form-label' %>
            <div class="col-10 col-sm-8">
                <%= f.text_field :full_name, class: 'form-control' %>
            </div>
        </div>
        <fieldset class="form-group row">
            <label class="form-check-label">
                <%= f.radio_button :is_coming, true, checked: true %>
                Will be there!
            </label>
            <label class="form-check-label">
                <%= f.radio_button :is_coming, false %>
                Can't make it
            </label>
        </fieldset>
        <fieldset class="form-group row">
            <label class="form-check-label">
                <%= f.radio_button :has_plus_one, true, checked: true %>
                I will be bringing someone
            </label>
            <label class="form-check-label">
                <%= f.radio_button :has_plus_one, false %>
                Goin' solo
            </label>
        </fieldset>
        <div class="form-group row">
            <%= f.label :plus_one_full_name, class: 'col-2 col-sm-4 col-form-label' %>
            <div class="col-10 col-sm-8">
                <%= f.text_field :plus_one_full_name, class: 'form-control' %>
            </div>
        </div>
        <%= f.submit %>
    <% end %>
</section>

app/views/rsvp/success.html.erb
<% if @rsvp.is_coming %>
    <h3>We'll see you there!</h3>
<% else %>
    <h3>Thank you for letting us know!</h3>
<% end %>